from command import Command
from vm import *

push119 = Command(CName.PUSH, 119)
storeX = Command(CName.STORE, 'x')
push2 = Command(CName.PUSH, 2)
storeY = Command(CName.STORE, 'y')
push1 = Command(CName.PUSH, 1)
storeR = Command(CName.STORE, 'r')
storeF = Command(CName.STORE, 'f')
loadF = Command(CName.LOAD, 'f')
cjmp2 = Command(CName.CJMP, 2)
jmp26 = Command(CName.JMP, 26)
loadX = Command(CName.LOAD, 'x')
loadY = Command(CName.LOAD, 'y')
rem = Command(CName.REM, None)
push0 = Command(CName.PUSH, 0)
eq = Command(CName.EQ, None)
jmp6 = Command(CName.JMP, 6)
jmp5 = Command(CName.JMP, 5)
add = Command(CName.ADD, None)
jmp4 = Command(CName.JMP, 4)
jmp1 = Command(CName.JMP, 1)
jmpM27 = Command(CName.JMP, -27)
quit = Command(CName.QUIT, None)
cl = [push119, storeX, push2, storeY, push1, storeR, push1, storeF, loadF, cjmp2, jmp26, loadX, loadY, rem, push0, eq, cjmp2, jmp6, push0, storeF, push0, storeR, jmp5, loadY, push1, add, storeY, loadX, loadY, eq, cjmp2, jmp4, push0, storeF, jmp1, jmpM27, quit]
print(l2s(cl))
vm = VM(cl)
print(vm.run())
