from command import Command
from vm import *

push20000000000000000 = Command(CName.PUSH, 20000000000000000)
storeV0 = Command(CName.STORE, 'v0')
push0 = Command(CName.PUSH, 0)
storeV1 = Command(CName.STORE, 'v1')
loadV0 = Command(CName.LOAD, 'v0')
storeV2 = Command(CName.STORE, 'v2')
loadV1 = Command(CName.LOAD, 'v1')
loadV2 = Command(CName.LOAD, 'v2')
neq = Command(CName.NEQ, None)
cjmp2 = Command(CName.CJMP, 2)
jmp44 = Command(CName.JMP, 44)
sub = Command(CName.SUB, None)
push2 = Command(CName.PUSH, 2)
rem = Command(CName.REM, None)
eq = Command(CName.EQ, None)
jmp10 = Command(CName.JMP, 10)
quo = Command(CName.DIV, None)
add = Command(CName.ADD, None)
storeV3 = Command(CName.STORE, 'v3')
jmp11 = Command(CName.JMP, 11)
loadV3 = Command(CName.LOAD, 'v3')
push1 = Command(CName.PUSH, 1)
mul = Command(CName.MUL, None)
gt = Command(CName.GT, None)
jmp6 = Command(CName.JMP, 6)
jmp3 = Command(CName.JMP, 3)
jmpM47 = Command(CName.JMP, -47)
quit = Command(CName.QUIT, None)
cl = [push20000000000000000, storeV0, push0, storeV1, loadV0, storeV2, loadV1, loadV2, neq, cjmp2, jmp44, loadV2, loadV1, sub, push2, rem, push0, eq, cjmp2, jmp10, loadV1, loadV2, loadV1, sub, push2, quo, add, storeV3, jmp11, loadV1, loadV2, loadV1, sub, push2, quo, add, push1, add, storeV3, loadV3, loadV3, mul, loadV0, gt, cjmp2, jmp6, loadV3, push1, sub, storeV2, jmp3, loadV3, storeV1, jmpM47, quit]
print(l2s(cl))
vm = VM(cl)
print(vm.run())
